[2022-09-25T06:56:27.699+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [queued]>
[2022-09-25T06:56:27.725+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [queued]>
[2022-09-25T06:56:27.726+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:27.726+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:27.727+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:27.770+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-04 00:00:00+00:00
[2022-09-25T06:56:27.783+0000] {standard_task_runner.py:54} INFO - Started process 1457 to run task
[2022-09-25T06:56:27.792+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-04T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpmj2anqbj']
[2022-09-25T06:56:27.795+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask model.migrate_to_dbt.view_data
[2022-09-25T06:56:27.797+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:27.955+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:28.103+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-04T00:00:00+00:00
[2022-09-25T06:56:28.104+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:28.105+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T06:56:28.134+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:28.139+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:28.139+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:28.165+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:28.171+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210104T000000, start_date=20220925T065627, end_date=20220925T065628
[2022-09-25T06:56:28.212+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 42 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 1457)
[2022-09-25T06:56:28.243+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:28.342+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:23.378+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [queued]>
[2022-09-25T12:33:23.414+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [queued]>
[2022-09-25T12:33:23.415+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:23.415+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:23.416+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:23.493+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-04 00:00:00+00:00
[2022-09-25T12:33:23.527+0000] {standard_task_runner.py:54} INFO - Started process 241 to run task
[2022-09-25T12:33:23.549+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-04T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmph8j6dlp_']
[2022-09-25T12:33:23.550+0000] {standard_task_runner.py:83} INFO - Job 36: Subtask model.migrate_to_dbt.view_data
[2022-09-25T12:33:23.552+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:23.761+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-04T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:23.924+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-04T00:00:00+00:00
[2022-09-25T12:33:23.926+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:23.927+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T12:33:23.948+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:23.952+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:23.954+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:23.975+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:23.983+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210104T000000, start_date=20220925T123323, end_date=20220925T123323
[2022-09-25T12:33:24.007+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 36 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 241)
[2022-09-25T12:33:24.049+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:24.194+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
