[2022-09-25T06:56:21.217+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [queued]>
[2022-09-25T06:56:21.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [queued]>
[2022-09-25T06:56:21.268+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:21.268+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:21.268+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:21.313+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-26 00:00:00+00:00
[2022-09-25T06:56:21.349+0000] {standard_task_runner.py:54} INFO - Started process 1373 to run task
[2022-09-25T06:56:21.357+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-26T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpu04oyq9z']
[2022-09-25T06:56:21.364+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T06:56:21.366+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:21.669+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:22.103+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-26T00:00:00+00:00
[2022-09-25T06:56:22.112+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:22.115+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T06:56:22.155+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:22.173+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:22.176+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:22.221+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:22.235+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201226T000000, start_date=20220925T065621, end_date=20220925T065622
[2022-09-25T06:56:22.290+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 1373)
[2022-09-25T06:56:22.342+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:22.518+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:17.973+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [queued]>
[2022-09-25T12:33:18.007+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [queued]>
[2022-09-25T12:33:18.007+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:18.007+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:18.007+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:18.032+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-26 00:00:00+00:00
[2022-09-25T12:33:18.042+0000] {standard_task_runner.py:54} INFO - Started process 154 to run task
[2022-09-25T12:33:18.046+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-26T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp247iyvhp']
[2022-09-25T12:33:18.047+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T12:33:18.048+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:18.170+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-26T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:18.316+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-26T00:00:00+00:00
[2022-09-25T12:33:18.319+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:18.319+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T12:33:18.356+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:18.358+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:18.359+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:18.391+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:18.399+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201226T000000, start_date=20220925T123317, end_date=20220925T123318
[2022-09-25T12:33:18.446+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 154)
[2022-09-25T12:33:18.501+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:18.568+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
