[2022-09-26T11:51:18.183+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2022-01-09T00:00:00+00:00 [queued]>
[2022-09-26T11:51:18.240+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2022-01-09T00:00:00+00:00 [queued]>
[2022-09-26T11:51:18.241+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T11:51:18.241+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-26T11:51:18.242+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-26T11:51:18.351+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2022-01-09 00:00:00+00:00
[2022-09-26T11:51:18.370+0000] {standard_task_runner.py:54} INFO - Started process 4254 to run task
[2022-09-26T11:51:18.405+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2022-01-09T00:00:00+00:00', '--job-id', '1526', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmplnsjzsob']
[2022-09-26T11:51:18.406+0000] {standard_task_runner.py:83} INFO - Job 1526: Subtask model.migrate_to_dbt.view_data
[2022-09-26T11:51:18.412+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-26T11:51:37.002+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1526 for task model.migrate_to_dbt.view_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 4254)
[2022-09-26T11:51:38.044+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-26T11:51:38.645+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
