[2022-09-25T12:23:23.921+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [queued]>
[2022-09-25T12:23:23.933+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [queued]>
[2022-09-25T12:23:23.933+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:23:23.934+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-25T12:23:23.934+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:23:23.953+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-05 00:00:00+00:00
[2022-09-25T12:23:23.959+0000] {standard_task_runner.py:54} INFO - Started process 171 to run task
[2022-09-25T12:23:23.963+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-05T00:00:00+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpm3x95fx8']
[2022-09-25T12:23:23.963+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask model.migrate_to_dbt.view_data
[2022-09-25T12:23:23.964+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:23:24.039+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [running]> on host 2768f2fff4c2
[2022-09-25T12:23:24.131+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-05T00:00:00+00:00
[2022-09-25T12:23:24.133+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:23:24.133+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T12:23:24.144+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:23:24.146+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:23:24.147+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:23:24.159+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:23:24.165+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210105T000000, start_date=20220925T122323, end_date=20220925T122324
[2022-09-25T12:23:24.179+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 92 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 171)
[2022-09-25T12:23:24.214+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:23:24.245+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T15:24:41.636+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [queued]>
[2022-09-25T15:24:41.682+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [queued]>
[2022-09-25T15:24:41.683+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:41.683+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-25T15:24:41.683+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:41.740+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-05 00:00:00+00:00
[2022-09-25T15:24:41.769+0000] {standard_task_runner.py:54} INFO - Started process 2382 to run task
[2022-09-25T15:24:41.778+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-05T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpgbc7dhr2']
[2022-09-25T15:24:41.780+0000] {standard_task_runner.py:83} INFO - Job 80: Subtask model.migrate_to_dbt.view_data
[2022-09-25T15:24:41.782+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T15:24:42.040+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-05T00:00:00+00:00 [running]> on host 3c654011b3f0
[2022-09-25T15:24:42.341+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-05T00:00:00+00:00
[2022-09-25T15:24:42.343+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T15:24:42.355+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T15:24:42.456+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T15:24:42.494+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T15:24:42.496+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T15:24:42.547+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T15:24:42.567+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210105T000000, start_date=20220925T152441, end_date=20220925T152442
[2022-09-25T15:24:42.628+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 2382)
[2022-09-25T15:24:42.688+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T15:24:43.115+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
