[2022-09-25T12:24:02.377+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [queued]>
[2022-09-25T12:24:02.436+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [queued]>
[2022-09-25T12:24:02.436+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:24:02.437+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:24:02.437+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:24:02.484+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-16 00:00:00+00:00
[2022-09-25T12:24:02.502+0000] {standard_task_runner.py:54} INFO - Started process 285 to run task
[2022-09-25T12:24:02.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-16T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpl90xexts']
[2022-09-25T12:24:02.509+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask model.migrate_to_dbt.view_data
[2022-09-25T12:24:02.511+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:24:02.709+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [running]> on host 2768f2fff4c2
[2022-09-25T12:24:02.859+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-16T00:00:00+00:00
[2022-09-25T12:24:02.861+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:24:02.863+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T12:24:02.902+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:24:02.911+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:24:02.918+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:24:02.968+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:24:02.981+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210116T000000, start_date=20220925T122402, end_date=20220925T122402
[2022-09-25T12:24:03.017+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 113 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 285)
[2022-09-25T12:24:03.052+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:24:03.153+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T15:24:51.727+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [queued]>
[2022-09-25T15:24:51.756+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [queued]>
[2022-09-25T15:24:51.757+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:51.758+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T15:24:51.758+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:51.782+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2021-01-16 00:00:00+00:00
[2022-09-25T15:24:51.788+0000] {standard_task_runner.py:54} INFO - Started process 2471 to run task
[2022-09-25T15:24:51.792+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2021-01-16T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpr714j4q5']
[2022-09-25T15:24:51.793+0000] {standard_task_runner.py:83} INFO - Job 103: Subtask model.migrate_to_dbt.view_data
[2022-09-25T15:24:51.794+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T15:24:51.912+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2021-01-16T00:00:00+00:00 [running]> on host 3c654011b3f0
[2022-09-25T15:24:52.064+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-16T00:00:00+00:00
[2022-09-25T15:24:52.066+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T15:24:52.067+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T15:24:52.085+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T15:24:52.089+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T15:24:52.091+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T15:24:52.117+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T15:24:52.125+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20210116T000000, start_date=20220925T152451, end_date=20220925T152452
[2022-09-25T15:24:52.148+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 2471)
[2022-09-25T15:24:52.164+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T15:24:52.224+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
