[2022-09-25T06:56:24.237+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [queued]>
[2022-09-25T06:56:24.287+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [queued]>
[2022-09-25T06:56:24.289+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:24.289+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:24.290+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:24.357+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-29 00:00:00+00:00
[2022-09-25T06:56:24.381+0000] {standard_task_runner.py:54} INFO - Started process 1404 to run task
[2022-09-25T06:56:24.407+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-29T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpgw_nhu9j']
[2022-09-25T06:56:24.409+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T06:56:24.428+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:24.685+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:24.965+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-29T00:00:00+00:00
[2022-09-25T06:56:24.969+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:24.975+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T06:56:25.023+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:25.030+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:25.032+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:25.074+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:25.090+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201229T000000, start_date=20220925T065624, end_date=20220925T065625
[2022-09-25T06:56:25.141+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 1404)
[2022-09-25T06:56:25.183+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:25.291+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:19.423+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [queued]>
[2022-09-25T12:33:19.452+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [queued]>
[2022-09-25T12:33:19.452+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:19.453+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:19.453+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:19.483+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-29 00:00:00+00:00
[2022-09-25T12:33:19.492+0000] {standard_task_runner.py:54} INFO - Started process 184 to run task
[2022-09-25T12:33:19.498+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-29T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpzwjizrge']
[2022-09-25T12:33:19.500+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T12:33:19.502+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:19.631+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-29T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:19.798+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-29T00:00:00+00:00
[2022-09-25T12:33:19.800+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:19.810+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T12:33:19.874+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:19.886+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:19.888+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:19.934+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:19.944+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201229T000000, start_date=20220925T123319, end_date=20220925T123319
[2022-09-25T12:33:19.991+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 184)
[2022-09-25T12:33:20.013+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:20.074+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
