[2022-09-25T12:23:20.855+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T12:23:20.874+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T12:23:20.874+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:23:20.874+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-25T12:23:20.875+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:23:20.900+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2020-12-27 00:00:00+00:00
[2022-09-25T12:23:20.906+0000] {standard_task_runner.py:54} INFO - Started process 138 to run task
[2022-09-25T12:23:20.910+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2020-12-27T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp6mjy1tjn']
[2022-09-25T12:23:20.912+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask model.migrate_to_dbt.view_data
[2022-09-25T12:23:20.913+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:23:21.002+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [running]> on host 2768f2fff4c2
[2022-09-25T12:23:21.092+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T00:00:00+00:00
[2022-09-25T12:23:21.093+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:23:21.095+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T12:23:21.114+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:23:21.116+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:23:21.116+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:23:21.131+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:23:21.135+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20201227T000000, start_date=20220925T122320, end_date=20220925T122321
[2022-09-25T12:23:21.154+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 138)
[2022-09-25T12:23:21.202+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:23:21.240+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T15:24:39.152+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T15:24:39.182+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T15:24:39.183+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:39.183+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2022-09-25T15:24:39.184+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T15:24:39.328+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.view_data> on 2020-12-27 00:00:00+00:00
[2022-09-25T15:24:39.343+0000] {standard_task_runner.py:54} INFO - Started process 2354 to run task
[2022-09-25T15:24:39.394+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.view_data', 'scheduled__2020-12-27T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpz57q56kl']
[2022-09-25T15:24:39.396+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask model.migrate_to_dbt.view_data
[2022-09-25T15:24:39.397+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T15:24:40.031+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.view_data scheduled__2020-12-27T00:00:00+00:00 [running]> on host 3c654011b3f0
[2022-09-25T15:24:40.568+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.view_data
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T00:00:00+00:00
[2022-09-25T15:24:40.580+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T15:24:40.581+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models view_data\n            ']
[2022-09-25T15:24:40.663+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T15:24:40.688+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T15:24:40.690+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T15:24:40.738+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T15:24:40.748+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dbt_dag, task_id=model.migrate_to_dbt.view_data, execution_date=20201227T000000, start_date=20220925T152439, end_date=20220925T152440
[2022-09-25T15:24:40.793+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 79 for task model.migrate_to_dbt.view_data (Bash command failed. The command returned a non-zero exit code 127.; 2354)
[2022-09-25T15:24:40.822+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T15:24:41.436+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
