[2022-09-25T06:56:24.825+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [queued]>
[2022-09-25T06:56:24.865+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [queued]>
[2022-09-25T06:56:24.866+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:24.866+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:24.867+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:24.915+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-30 00:00:00+00:00
[2022-09-25T06:56:24.930+0000] {standard_task_runner.py:54} INFO - Started process 1412 to run task
[2022-09-25T06:56:24.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-30T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpxwdqthzq']
[2022-09-25T06:56:24.947+0000] {standard_task_runner.py:83} INFO - Job 31: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T06:56:24.949+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:25.234+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:25.495+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-30T00:00:00+00:00
[2022-09-25T06:56:25.497+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:25.498+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T06:56:25.523+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:25.528+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:25.529+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:25.555+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:25.561+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201230T000000, start_date=20220925T065624, end_date=20220925T065625
[2022-09-25T06:56:25.585+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 1412)
[2022-09-25T06:56:25.614+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:25.846+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:20.063+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [queued]>
[2022-09-25T12:33:20.082+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [queued]>
[2022-09-25T12:33:20.082+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:20.082+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:20.082+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:20.128+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-30 00:00:00+00:00
[2022-09-25T12:33:20.176+0000] {standard_task_runner.py:54} INFO - Started process 193 to run task
[2022-09-25T12:33:20.182+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-30T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpur_uosb4']
[2022-09-25T12:33:20.183+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T12:33:20.184+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:20.298+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-30T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:20.425+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-30T00:00:00+00:00
[2022-09-25T12:33:20.427+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:20.428+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T12:33:20.459+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:20.464+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:20.466+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:20.485+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:20.493+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201230T000000, start_date=20220925T123320, end_date=20220925T123320
[2022-09-25T12:33:20.516+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 26 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 193)
[2022-09-25T12:33:20.534+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:20.616+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
