[2022-09-25T06:56:27.209+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [queued]>
[2022-09-25T06:56:27.232+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [queued]>
[2022-09-25T06:56:27.233+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:27.233+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:27.233+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:27.265+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2021-01-03 00:00:00+00:00
[2022-09-25T06:56:27.278+0000] {standard_task_runner.py:54} INFO - Started process 1449 to run task
[2022-09-25T06:56:27.285+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2021-01-03T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp2hw17_x8']
[2022-09-25T06:56:27.287+0000] {standard_task_runner.py:83} INFO - Job 40: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T06:56:27.288+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:27.400+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:27.527+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T00:00:00+00:00
[2022-09-25T06:56:27.529+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:27.530+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T06:56:27.562+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:27.566+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:27.567+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:27.588+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:27.597+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20210103T000000, start_date=20220925T065627, end_date=20220925T065627
[2022-09-25T06:56:27.641+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 40 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 1449)
[2022-09-25T06:56:27.696+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:27.808+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:22.541+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [queued]>
[2022-09-25T12:33:22.570+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [queued]>
[2022-09-25T12:33:22.571+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:22.572+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:22.572+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:22.624+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2021-01-03 00:00:00+00:00
[2022-09-25T12:33:22.637+0000] {standard_task_runner.py:54} INFO - Started process 232 to run task
[2022-09-25T12:33:22.645+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2021-01-03T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpnrg2_fzm']
[2022-09-25T12:33:22.646+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T12:33:22.647+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:22.830+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2021-01-03T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:22.998+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T00:00:00+00:00
[2022-09-25T12:33:23.000+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:23.001+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T12:33:23.038+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:23.042+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:23.043+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:23.074+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:23.080+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20210103T000000, start_date=20220925T123322, end_date=20220925T123323
[2022-09-25T12:33:23.118+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 232)
[2022-09-25T12:33:23.150+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:23.383+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
