[2022-09-25T06:56:22.225+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T06:56:22.264+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T06:56:22.264+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:22.265+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T06:56:22.265+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T06:56:22.335+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-27 00:00:00+00:00
[2022-09-25T06:56:22.357+0000] {standard_task_runner.py:54} INFO - Started process 1389 to run task
[2022-09-25T06:56:22.389+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-27T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp688ho_zw']
[2022-09-25T06:56:22.392+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T06:56:22.403+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T06:56:22.844+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [running]> on host 5aeb3e9582c2
[2022-09-25T06:56:23.275+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T00:00:00+00:00
[2022-09-25T06:56:23.288+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T06:56:23.290+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T06:56:23.361+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T06:56:23.383+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T06:56:23.385+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T06:56:23.446+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T06:56:23.456+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201227T000000, start_date=20220925T065622, end_date=20220925T065623
[2022-09-25T06:56:23.510+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 1389)
[2022-09-25T06:56:23.562+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T06:56:23.752+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-25T12:33:18.570+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T12:33:18.600+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [queued]>
[2022-09-25T12:33:18.602+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:18.602+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-09-25T12:33:18.602+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:33:18.629+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): model.migrate_to_dbt.cast_obj> on 2020-12-27 00:00:00+00:00
[2022-09-25T12:33:18.640+0000] {standard_task_runner.py:54} INFO - Started process 168 to run task
[2022-09-25T12:33:18.645+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_dag', 'model.migrate_to_dbt.cast_obj', 'scheduled__2020-12-27T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmptbgrrn0m']
[2022-09-25T12:33:18.647+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask model.migrate_to_dbt.cast_obj
[2022-09-25T12:33:18.649+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dbt_dag.py
[2022-09-25T12:33:18.755+0000] {task_command.py:384} INFO - Running <TaskInstance: dbt_dag.model.migrate_to_dbt.cast_obj scheduled__2020-12-27T00:00:00+00:00 [running]> on host c138e22c1d18
[2022-09-25T12:33:18.939+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=isaaclucky88@gmail.com
AIRFLOW_CTX_DAG_OWNER=astronomer
AIRFLOW_CTX_DAG_ID=dbt_dag
AIRFLOW_CTX_TASK_ID=model.migrate_to_dbt.cast_obj
AIRFLOW_CTX_EXECUTION_DATE=2020-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-12-27T00:00:00+00:00
[2022-09-25T12:33:18.940+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:33:18.941+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            cd /opt/***/migrate_to_dbt &&\n            dbt --no-write-json run --target prod --models cast_obj\n            ']
[2022-09-25T12:33:18.965+0000] {subprocess.py:86} INFO - Output:
[2022-09-25T12:33:18.968+0000] {subprocess.py:93} INFO - /bin/bash: line 3: dbt: command not found
[2022-09-25T12:33:18.969+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-09-25T12:33:18.997+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-09-25T12:33:19.006+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_dag, task_id=model.migrate_to_dbt.cast_obj, execution_date=20201227T000000, start_date=20220925T123318, end_date=20220925T123319
[2022-09-25T12:33:19.028+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task model.migrate_to_dbt.cast_obj (Bash command failed. The command returned a non-zero exit code 127.; 168)
[2022-09-25T12:33:19.058+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-25T12:33:19.252+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
